### DISCUSSION TITLE
Conda package

### DISCUSSION THREAD

**Discussion by riziles** [r0x0r/pywebview#1302] [Ideas]
This project is amazing and deserves so many more stars.

I agree with @juanfcocontreras 's [comment](https://github.com/r0x0r/pywebview/issues/1106#issue-1680595302) that we'd probably see much wider adoption if there was Conda package available. I've never made one before, but I took a stab at using [Grayskull](https://github.com/conda/grayskull) to generate a `meta.yaml` file. It actually worked quite well, but I made some modifications to the output because I only needed it to work on Windows and I wanted to avoid accidentally including other dependencies  (see example below). Posting it hear in case any other users might find it useful. Full disclosure: I don't really know what I'm doing, but it worked.

To run:
1. save this as `meta.yaml` in an empty folder or better yet: build one yourself using `grayskull`
2. **In your `base` environment:** run `conda build {{folder name in step 1}}  --output-folder {{some other folder}}` 
3.  If it works, you should be able to install to any environment now using `conda install -c file:///C:{{folder from step 2}}/ --override-channels`

```yaml
{% set name = "pywebview" %}
{% set version = "4.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pywebview-{{ version }}.tar.gz
  sha256: ea4c517e9265fadfd77937facb67787c07425d303b00b9d5c3a401bbb4576941

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python
    - pythonnet  # [win]
    - proxy-tools
    - bottle
    - typing-extensions

test:
  imports:
    - webview
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Build GUI for your Python program with JavaScript, HTML, and CSS
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - optik-aper
```
