### ISSUE TITLE
Support transparency with blurred background.

### ISSUE THREAD

**Issue by NevermindNilas** [r0x0r/pywebview#1354]
### Specification
- pywebview version: 5.0.5 ( latest available through pip install )
- operating system: Windows 11
- web renderer: Chromium

### Description
Basically revisiting this [issue](https://github.com/r0x0r/pywebview/issues/935) without necroposting.
I would love to find out if it is possible to have a blurred background with semi-transparency.

```py
import webview

window = webview.create_window(
    "web/main.html",
    transparent=True,
    vibrancy=True,
    resizable=False,
    width=1366,
    height=768,
)

webview.start()
```

```css
        body {
            overflow: hidden;
            margin: 0;
            background-color: rgba(255, 255, 255, 0.2);
            backdrop-filter: blur(10px);
        }
```
An example through File Explorer + MICA:
![image](https://github.com/r0x0r/pywebview/assets/128264457/743866ce-5e8c-41f7-8bd1-f5d5ba222385)

if there's no direct way, maybe a similar approach to [PythonBlurBehind](https://github.com/Peticali/PythonBlurBehind) could work?

### Practicalities

- YES: I am willing to work on this issue myself.
